# -*- coding: utf-8 -*-
"""File Read & Write.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYpLcCp5PQGTEgAT7pfGiZSwu5CYFZin
"""

# File Read & Write Challenge with Error Handling

def file_read_write():
    try:
        # Ask the user for the input file name
        input_filename = input("Enter the name of the file to read: ").strip()

        # Try reading the file
        with open(input_filename, 'r', encoding='utf-8') as infile:
            content = infile.read()

        # Modify content (example: make it uppercase)
        modified_content = content.upper()

        # Ask for output file name
        output_filename = input("Enter the name of the new file to write to: ").strip()

        # Write the modified content to the new file
        with open(output_filename, 'w', encoding='utf-8') as outfile:
            outfile.write(modified_content)

        print(f"✅ File '{input_filename}' successfully read and modified version saved to '{output_filename}'.")

    except FileNotFoundError:
        print("❌ Error: The file you entered does not exist. Please check the filename and try again.")
    except PermissionError:
        print("❌ Error: You do not have permission to read or write this file.")
    except Exception as e:
        print(f"⚠️ An unexpected error occurred: {e}")

# Run the function
file_read_write()